language: android
notifications:
  email: false
android:
  components:
  - tools
  - build-tools-22.0.1
  - android-21
  - extra-android-support
jdk:
  - oraclejdk7
after_script:
  - ./gradlew clean assemble jacocoTestReport coveralls